[default]
solc_version = "0.8.13"
optimizer = true
optimizer_runs = 200
via_ir = true
fuzz_runs = 256
src = 'contracts'
out = 'out'
libs = ['node_modules']
test = 'test/foundry'
remappings = [
    'ds-test=lib/ds-test/src/',
    'forge-std=lib/forge-std/src/',
]


# See more config options https://github.com/gakonst/foundry/tree/master/config